### ISSUE TITLE
Path error while using

### ISSUE THREAD

**Issue by YumiChow** [Ray-D-Song/markdown-translator#1]
When I tried to use this plugin in VSCode to translate a markdown file, it popped up a window saying that the path cannot be found. This seems to be a problem with relative / absolute path.

![image](https://github.com/user-attachments/assets/ef32d996-781e-44fc-8118-67404600bd7d)

**Comment by Ray-D-Song** [comment]
I'm sorry for replying just now, but I have tested it on both Windows and macOS, and it works fine. Can you provide a minimal reproduction?

**Comment by YumiChow** [comment]
Thanks for your response. I have located the problem and solved it.

My environment:

- Windows 11 Build 22631.3958
- VSCode 1.93.0
- Node.js v18.17.1

In my environment, `editor.document.uri.fsPath` on line 55 of `src/index.ts` gets the Windows file directory format, which uses back slashes. This leads to problems with path processing with forward slash on lines 58 and 61.

I suggest using the path module of Node.js to perform path operations. Use:
```
const fileName = path.basename(from)
```
to replace line 58:
```
const fileName = from.split('/').pop() || ''
```
and use:
```
const to = path.join(toDir, fileName)
```
to replace line 61:
```
const to = `${toDir}/${fileName}`;
```

Since it is not clear how many times you have similar problems in your code, I will only raise the issue and solution here, and will not submit a Pull Request. I hope you can solve all similar file path back & forward slash issues in your code and update as soon as possible, thank you.

**Comment by Ray-D-Song** [comment]
Thank you for your kind help, which also taught me how to handle paths correctly using nodejs.
I have tried my best to fix the path, as this is a small tool I developed for myself, so it has not undergone thorough testing.
